image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install && abtnode init -f --no-https
    command: abtnode start
ports:
  - port: 8080
    onOpen: ignore
  - port: 4430
    onOpen: ignore
  - port: 8089
    onOpen: ignore
  - port: 8090
    onOpen: ignore
